module.exports.sconfig = {
    projectUrl: 'https://cleanroom.cmsw.cortex.deloitte.com/projects',
    projectUrlDev: 'https://cleanroom.dev.cortex.deloitte.com/projects/',
    cleanRoomDevURI: 'https://cleanroom.dev.cortex.deloitte.com/',
    authToken: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InFtYTdtMm9FOVQzNW11R3BiRUpBT0xkM0dVRSIsImtpZCI6InFtYTdtMm9FOVQzNW11R3BiRUpBT0xkM0dVRSJ9.eyJhdWQiOiJjMTIxZDYwMy05ZmY1LTQ1ZTEtOWM0Mi0wZTI0OGFmOTM2MjIiLCJpc3MiOiJodHRwczovL2R0dHN0c3N0YWdlLmRlbG9pdHRlcmVzb3VyY2VzLmNvbS9hZGZzIiwiaWF0IjoxNTc4ODkwMDQ4LCJleHAiOjE1Nzg4OTM2NDgsImF1dGhfdGltZSI6MTU3ODg5MDA0OCwibm9uY2UiOiJhMzU0Y2Y2MGZkOWU0M2NhYTYxNDEwYjVhNDA3NTVmNCIsInN1YiI6Inp2UWc0UEJxQ0orV082TjB4eHdWZERsamJHdjJITnBkREYxeDF2T0ZuMTQ9IiwidXBuIjoiYWZhaGVlbUBkZWxvaXR0ZS5jb20iLCJ1bmlxdWVfbmFtZSI6IkZhaGVlbSwgQXNhZCIsInB3ZF91cmwiOiJodHRwczovL2R0dHN0c3N0YWdlLmRlbG9pdHRlcmVzb3VyY2VzLmNvbS9hZGZzL3BvcnRhbC91cGRhdGVwYXNzd29yZC8iLCJwd2RfZXhwIjoiNjczMzY1OSIsInNpZCI6IlMtMS01LTIxLTIzODQ0NzI3Ni0xMDQwODYxOTIzLTE4NTA5NTI3ODgtMjY3MjY4OSJ9.Ds99F_8I6OAyjTJKM1aHeDZzB2leYLaqm0IoP3dp7laAXGcI7NeM-DY1Rv6y2hNeB-JK2Hhqjkv2dIft8avzNF7MkQh41XDmcfcfaVzsyPiRSZyT69CinrOaBpTtoZDusYYja9z8oHyMmefFpTV_7tGbmciOch0Mq1Csq57bJ9mqsp6QHBt7IY3KShdihR8bFj94w52ORVv1imdaiwF_j7kbiPRRMifuEq4IRfV39gIbztdP5nC1a_XvuA2bbSKKMqr4IrW6EukN3A64UTsA86P64Lh_X4HIA6I-qfxuM2tRlIJa2n8-ihJb9Dca5VLE5llidy8vpkyHz5FErxayZg',
    testDataDir : '',
    usernameDeloitte:"cortextstact06@deloitte.com",
    proxyAddress : '10.169.4.222:8080',
    shouldUseProxy : false,
    shouldQuitDriver : false,
    chromePluginUrl: 'chrome-extension://edffagcaebclmkmlmjiihgolpbgajjof/index.html',
    usernameLogin:"srirajg@deloitte.com",
    passwordLogin:"chamo@mile1994",
    goHeadLess: false,
    user_id: "Cortextstact06",
    password: "BACvzD3hR6LYqX2",
    user_id_temp: `srirajg@deloitte.com`,
    password_temp: `chamo@mile1994`,
    user_id_aman : `amanagarw@deloitte.com`,
    user_id_07: "cortextstact07@deloitte.com",
    user_pass_07: "m5anwU^GyC@R8P+%",
    user_id_08: "cortextstact08@deloitte.com",
    user_pass_08: "M8%Md6X2&WSQM9B&",
    user_id_09: "cortextstact09@deloitte.com",
    user_pass_09: "U?eM4HQf9cgnR%@q",
    user_id_10: "cortextstact10@deloitte.com",
    user_pass_10: "VC>cZEz7DGD8hyQd",
    user_id_external: "cortexuat3@gmail.com",
    user_pass_external: "Deloitte@1",
    user_role_data_analyst: "Data Analyst"
};